---
title: "Design-Weighted"
author: "Lauren Berny"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(csSampling)
library(dplyr)
library(brms)
library(rstan)
library(survey)
library(cmdstanr)
library(tidyverse)
library(ggeffects)
library(lme4)
library(merTools)
library(labelled)
library(sjPlot)
library(Metrics)
library(janitor)
library(here)
library(rio)
```

```{r}

load(here("data", "combined_clean.RData"))

dat <- full %>% 
 mutate(across(region:age, as.factor)) %>%
 filter(wave==4) %>% 
 filter(!is.na(weight)) %>% 
 filter(!is.na(sex)) %>% 
 filter(!is.na(age)) %>% 
 filter(!is.na(eprod_edsd))

dat <- dat %>% 
  mutate(strata = 1000 * as.numeric(region) + 
                   100 * as.numeric(age) + 
                    10 * as.numeric(sex) + 
                     1 * as.numeric(race_ethnicity))

n_distinct(dat$strata)
```



# Wave 4

## Define priors
```{r}
path_priors <- c(
  # logit scale
  prior(normal(0, 2), class = Intercept),
  #prior(normal(0, 2), class = b),
  # variance components
  prior(inv_gamma(2, 2), class = sd))
```


## Survey rep object
```{r}
dat$wt_norm <- dat$weight*(length(dat$weight)/sum(dat$weight))

design_sp1 <- svrepdesign(
  data = dat,
  type = "Fay",
  rho = 0.3,
  repweights = dat[, grep("^rep_weight_[0-9]+$", names(dat))],
  weights = ~wt_norm,
  mse = TRUE)

# Check mean of weights from subpop survey design object
summary(design_sp1$pweights)
# Calibrate weights so the mean=1
design_sp1 <- calibrate(design_sp1,
                        ~ 1,
                        c(`(Intercept)` = length(design_sp1$pweights)),
                        compress = FALSE)
# Check mean after calibration
summary(design_sp1$pweights) # Mean=1
```

## Null Model

```{r}
# Write and save Stan file
stancode_pyMDE_m1 <- make_stancode(
  brmsformula(
    as.factor(eprod_edsd)| weights(wt_norm) ~ 
      1 + (1 | strata)
    ), 
  data = dat,
  prior = path_priors,
  family = bernoulli(link="logit"),
  save_model = "brms_pyMDE_m1.stan")
# Load the Stan file
modbrms_pyMDE_m1 <- stan_model("brms_pyMDE_m1.stan")

# Set up data
databrms_pyMDE_m1 <- make_standata(
  brmsformula(
    as.factor(eprod_edsd)| weights(wt_norm) ~ 
      1 + (1 | strata)
    ),
  data = design_sp1$variables,
  prior = path_priors,
  family = bernoulli(link="logit"))
# Set Stan model weights = survey design weights
databrms_pyMDE_m1$weights <- design_sp1$pweights


set.seed(828) # for reproducible results
pyMDE_m1 <- cs_sampling(
  svydes = design_sp1, # use the subpop-defined survey object
  mod_stan = modbrms_pyMDE_m1,
  data_stan = databrms_pyMDE_m1,
  ctrl_stan = list(chains = 4,
                   iter = 8000, # 16,000 total iterations (8,000 post-warmup)
                   warmup = 4000, # 8,000 warmups
                   prior = path_priors,
                   backend = "cmdstanr",
                   threads = threading(2),
                   thin = 1),
  rep_design = TRUE,
  sampling_args = list(cores = 4))
```

```{r}
save(pyMDE_m1, file = "pyMDE_m1.RData")
```

Next!!!!

```{r}
logit2prob <- function(logit) {
  odds = exp(logit)
  prob = odds / (1 + odds)
  return(prob)
}
```


```{r}
select <- dplyr::select
# Get strata counts (N) and merge with groupName
# Past-year MDE
group_count_pyMDE <- dat %>% #wave 4
 mutate(strata = as.factor(strata)) %>% 
  count('strata') %>% 
  mutate(groupID = strata) %>% 
  select(groupID, freq)

# Create combined counts table
group_count_overall <- group_count_pyMDE %>% 
  mutate(n_pyMDE = freq) %>% 
#  mutate(n_ltMDE = group_count_ltMDE$freq) %>% 
  select(groupID, n_pyMDE)

group_count_region <- dat %>% 
  mutate(strata = as.factor(strata)) %>% 
  count(c("strata", "region")) %>% 
  pivot_wider(names_from = "region", values_from = "freq") %>% 
  rowwise() %>%
  mutate(overall = sum(c(`Northeast`, `Midwest`, `West`, `South`), 
                       na.rm = TRUE),
         groupID = strata) %>% 
  select(groupID, overall, `Northeast`, `Midwest`, 
         `West`, `South`)
```

# Wave 7
```{r}

load(here("data", "combined_clean.RData"))
```

```{r}
dat <- full %>% 
 dplyr::mutate(across(region:age, as.factor)) %>%
 filter(wave==7) %>% 
 filter(!is.na(weight)) %>% 
 filter(!is.na(sex)) %>% 
 filter(!is.na(age)) %>% 
 filter(!is.na(eprod_edsd))

dat <- dat %>% 
  mutate(strata = 1000 * as.numeric(region) + 
                   100 * as.numeric(age) + 
                    10 * as.numeric(sex) + 
                     1 * as.numeric(race_ethnicity))

n_distinct(dat$strata)
```

```{r}
dat$wt_norm <- dat$weight*(length(dat$weight)/sum(dat$weight))

design_sp2 <- svrepdesign(
  data = dat,
  type = "Fay",
  rho = 0.3,
  repweights = dat[, grep("^rep_weight_[0-9]+$", names(dat))],
  weights = ~wt_norm,
  mse = TRUE)

# Check mean of weights from subpop survey design object
summary(design_sp2$pweights)
# Calibrate weights so the mean=1
design_sp2 <- calibrate(design_sp2,
                        ~ 1,
                        c(`(Intercept)` = length(design_sp2$pweights)),
                        compress = FALSE)
# Check mean after calibration
summary(design_sp2$pweights) # Mean=1
```

```{r}
# Write and save Stan file
stancode_pyMDE_m3 <- make_stancode(
  brmsformula(
    as.factor(eprod_edsd)| weights(wt_norm) ~ 
      1 + (1 | strata)
    ), 
  data = dat,
  prior = path_priors,
  family = bernoulli(link="logit"),
  save_model = "brms_pyMDE_m3.stan")
# Load the Stan file
modbrms_pyMDE_m3 <- stan_model("brms_pyMDE_m3.stan")

# Set up data
databrms_pyMDE_m3 <- make_standata(
  brmsformula(
    as.factor(eprod_edsd)| weights(wt_norm) ~ 
      1 + (1 | strata)
    ),
  data = design_sp2$variables,
  prior = path_priors,
  family = bernoulli(link="logit"))
# Set Stan model weights = survey design weights
databrms_pyMDE_m3$weights <- design_sp2$pweights


set.seed(828) # for reproducible results
pyMDE_m3 <- cs_sampling(
  svydes = design_sp2, # use the subpop-defined survey object
  mod_stan = modbrms_pyMDE_m3,
  data_stan = databrms_pyMDE_m3,
  ctrl_stan = list(chains = 4,
                   iter = 8000, # 16,000 total iterations (8,000 post-warmup)
                   warmup = 4000, # 8,000 warmups
                   prior = path_priors,
                   backend = "cmdstanr",
                   threads = threading(2),
                   thin = 1),
  rep_design = TRUE,
  sampling_args = list(cores = 4))
```

```{r}
save(pyMDE_m3, file = "pyMDE_m3.RDS")
```

