---
title: "Untitled"
author: "Lauren Berny"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(here)
library(rio)
library(tidyverse)
library(janitor)
library(srvyr)
library(gtsummary)
library(survey)

load("C:/Users/laure/OneDrive - University Of Oregon/2025 SPR Cup/Analysis/36498-4001-Data.rda")
load("C:/Users/laure/OneDrive - University Of Oregon/2025 SPR Cup/Analysis/36498-7001-Data.rda")
load("C:/Users/laure/OneDrive - University Of Oregon/2025 SPR Cup/Analysis/36498-4321-Data.rda")
load("C:/Users/laure/OneDrive - University Of Oregon/2025 SPR Cup/Analysis/36498-7331-Data.rda")

wave4 <- da36498.4001
wave7 <- da36498.7001
wave4_wghts <- da36498.4321
wave7_wghts <- da36498.7331 %>% 
 select(PERSONID:R07_A_C07WGT)

wave4 <- left_join(wave4_wghts, wave4, by = "PERSONID")
wave4$R04_AM0040 <- as.numeric(wave4$R04_AM0040)

wave7_wghts$PERSONID <- as.character(wave7_wghts$PERSONID)
wave7$PERSONID <- as.character(wave7$PERSONID)
wave7_wghts$PERSONID <- trimws(wave7_wghts$PERSONID)
wave7$PERSONID <- trimws(wave7$PERSONID)
wave7 <- left_join(wave7_wghts, wave7, by = "PERSONID")
wave7$R07_AM0040 <- as.numeric(wave7$R07_AM0040)
# R04_A_C04WGT R07_A_C07WGT
```


```{r}
# path_svy4 <- svydesign(
#   id = ~VARPSU,          # PSU (Primary Sampling Unit) Indicator for Variance Estimation
#   strata = ~VARSTRAT,    # Stratum Indicator for Variance Estimation
#   weights = ~R04_A_C04WGT,  # Cross-sectional weights
#   data = wave4, 
#   nest = TRUE            # Ensures correct nesting of PSU within strata
# )

path_svy4 <- svrepdesign(
  data = wave4,
  type = "Fay",
  rho = 0.3,
  repweights = wave4[, grep("^R04_A_C04WGT[0-9]+$", names(wave4))],
  weights = ~R04_A_C04WGT,
  mse = TRUE)

path_svy4 %>% 
  tbl_svysummary(include = c(R04_AM0040, R04X_CB_REGION, R04R_A_HISP_IMP, R04R_A_RACECAT3_IMP,
                             R04R_A_SEXORIENT2, R04R_A_SEX, R04R_A_AGECAT6, 
                             # R04_AV1004, R04_AV1002_12M,
                             R04R_A_P30D_EPRODS, R04R_A_EDY_EPRODS, R04R_A_SDY_EPRODS, R04R_A_CUR_EDSD_EPRODS,
                             R04R_A_CUR_ESTD_EPRODS),
                 label = list(R04_AM0040 = "Social Position",
                              R04X_CB_REGION = "Census Region",
                              R04R_A_HISP_IMP = "Hispanic Ethnicity",
                              R04R_A_RACECAT3_IMP = "Race",
                              R04R_A_SEXORIENT2 = "Sexual Orientation",
                              R04R_A_SEX = "Sex",
                              R04R_A_AGECAT6 = "Age",
                              # R04_AV1004 = "In the past 30 days, used an electronic nicotine product, even one or two times",
                              # R04_AV1002_12M = "In the past 12 months, used an electronic nicotine product, even one or two times",
                              R04R_A_P30D_EPRODS = "Past 30 Day Electronic Nicotine Product User",
                              R04R_A_EDY_EPRODS = "Current Every Day Electronic Nicotine Product User",
                              R04R_A_SDY_EPRODS = "Current Some Day Electronic Nicotine Product User",
                              R04R_A_CUR_EDSD_EPRODS = "Current Every Day/Some Day Electronic Nicotine Product User",
                              R04R_A_CUR_ESTD_EPRODS = "Current Established Electronic Nicotine Product User"),
            missing = "no", 
            type = list(R04_AM0040 ~ "continuous"),
            statistic = list(all_continuous() ~ "{mean} ({sd})", 
                                all_categorical() ~ "{p}%"),
            digits = list(all_categorical() ~ 1,
                          all_continuous() ~ 1))


```


```{r}
path_svy7 <- svydesign(
  id = ~VARPSU,          # PSU (Primary Sampling Unit) Indicator for Variance Estimation
  strata = ~VARSTRAT,    # Stratum Indicator for Variance Estimation
  weights = ~R07_A_C07WGT,  # Cross-sectional weights
  data = wave7, 
  nest = TRUE            # Ensures correct nesting of PSU within strata
)

path_svy7 %>% 
 tbl_svysummary(include = c(R07_AM0040, R07X_CB_REGION, R07R_A_HISP_IMP, R07R_A_RACECAT3_IMP,
                            R07R_A_SEXORIENT2, R07R_A_SEX, R07R_A_AGECAT6, 
                            # R07_AV1004, R07_AV1002_12M,
                            R07R_A_P30D_EPRODS, R07R_A_EDY_EPRODS, R07R_A_SDY_EPRODS, R07R_A_CUR_EDSD_EPRODS,
                            R07R_A_CUR_ESTD_EPRODS),
                label = list(R07_AM0040 = "Social Position",
                             R07X_CB_REGION = "Census Region",
                             R07R_A_HISP_IMP = "Hispanic Ethnicity",
                             R07R_A_RACECAT3_IMP = "Race",
                             R07R_A_SEXORIENT2 = "Sexual Orientation",
                             R07R_A_SEX = "Sex",
                             R07R_A_AGECAT6 = "Age",
                             # R07_AV1004 = "In the past 30 days, used an electronic nicotine product, even one or two times",
                             # R07_AV1002_12M = "In the past 12 months, used an electronic nicotine product, even one or two times",
                             R07R_A_P30D_EPRODS = "Past 30 Day Electronic Nicotine Product User",
                             R07R_A_EDY_EPRODS = "Current Every Day Electronic Nicotine Product User",
                             R07R_A_SDY_EPRODS = "Current Some Day Electronic Nicotine Product User",
                             R07R_A_CUR_EDSD_EPRODS = "Current Every Day/Some Day Electronic Nicotine Product User",
                             R07R_A_CUR_ESTD_EPRODS = "Current Established Electronic Nicotine Product User"),
                #missing = "no", 
                type = list(R07_AM0040 ~ "continuous"),
                statistic = list(all_continuous() ~ "{mean} ({sd})", 
                                 all_categorical() ~ "{p}%"),
                digits = list(all_categorical() ~ 1,
                              all_continuous() ~ 1))
```

# For fun:
Ran design-weighted models in Stata (not MAIHDA), adjusted for age.

```{r}
# Create data for Wave 4
wave4_data <- data.frame(
  intersection_strata = c("Male 1 = White alone", "Male 2 = Black alone", "Male 3 = Other",
                          "Female 1 = White alone", "Female 2 = Black alone", "Female 3 = Other"),
  probability = c(0.043336, 0.0231927, 0.0302676, 0.0295101, 0.0151107, 0.019689),
  ci_lower = c(0.039616, 0.0164322, 0.0237686, 0.0267088, 0.0106783, 0.0142781),
  ci_upper = c(0.047056, 0.0299532, 0.0367666, 0.0323115, 0.0195431, 0.0250999),
  wave = "Wave 4"
)

# Create data for Wave 7
wave7_data <- data.frame(
  intersection_strata = c("Male 1 = White alone", "Male 2 = Black alone", "Male 3 = Other",
                          "Female 1 = White alone", "Female 2 = Black alone", "Female 3 = Other"),
  probability = c(0.0690541, 0.0466974, 0.0549721, 0.0610575, 0.0310092, 0.0422495),
  ci_lower = c(0.0630737, 0.0378059, 0.0450501, 0.0568774, 0.0248685, 0.0346288),
  ci_upper = c(0.0750345, 0.0555888, 0.0648941, 0.0652375, 0.0371498, 0.0498701),
  wave = "Wave 7"
)

# Combine both data frames
combined_data <- bind_rows(wave4_data, wave7_data)

# Plot using ggplot2
ggplot(combined_data, aes(x = probability, y = intersection_strata, color = wave)) +
  geom_point(size = 3) +  # Plot the predicted probabilities as points
  geom_errorbarh(aes(xmin = ci_lower, xmax = ci_upper), height = 0.2) +  # Add horizontal CI bars
  labs(
    title = "Predicted Prevalence by Intersectional Strata for Wave 4 and Wave 7",
    x = "Predicted Prevalence of Being an Established Electronic Nicotine Product User",
    y = "Intersectional Strata",
    color = "Wave"
  ) +
  theme_minimal() +
  theme(legend.position = "top")

```

